### PR TITLE
mpv like query parsing

### PR DESCRIPTION
**Pull request by christoph-heinrich**
This can deal with quotes using `"` and `'` and preserves whitespace inside the quotes instead of replacing it with spaces.
It also fails parsing when mpv fails.

In practice the whitespace thing doesn't really make a difference because it's not possible to type `\t` in the query, but maybe it'll become relevant at some point.

I haven't looked at the implementation inside mpv, so maybe there are some edge cases where it behaves differently, but it should be pretty close.

### CODE REVIEW

**Comment by po5** [comment]
I don't like the behavior when typing a quoted string, you type the first quote and it's spinning, then as you're typing the word it's still spinning (into nowhere), and only shows results when you finally close the quote.

**Comment by christoph-heinrich** [comment]
Better?

**Comment by po5** [comment]
`parts[#parts + 1] = query:sub(pos + 1, -1)` before `return parts` keeps the search-as-you-type niceness. Don't think this breaks anything, you tell me.

**Comment by christoph-heinrich** [comment]
That's a good idea. The original code didn't do that, but I like it.

**Pull request merged**
